def main(N=100):
    
    S = set()
    for a in range(2, N+1):
        for b in range(2, N+1):
            S.add(a**b)
    
    print(f"The number of distinct terms generated by a^b for 2 <= a, b <= {N} is:", len(S))
    return len(S)

if __name__ == "__main__":
    main()